services:
  postgres_sorteador_app: 
    image: postgres
    container_name: postgres_sorteador_app
    restart: always
    ports:
      - 2345:5432
    env_file:
      - ./back-end/.env
    volumes:
      - postgres_sorteador_app:/var/lib/postgresql/data  

  node_sorteador_app:
    container_name: node_sorteador_app
    build: ./back-end
    ports:
      - 5000:5000
    depends_on:
      - postgres_sorteador_app
    env_file:
      - ./back-end/.env

  react_sorteador_app:
    container_name: react_sorteador_app
    build: ./front-end
    volumes: 
      - build_react:/var/www/html

  nginx_sorteador_app:
    container_name: nginx-sorteador_app
    build: ./nginx
    ports:
      - 8080:80
    volumes:
      - build_react:/var/www/html 
    depends_on:
      - postgres_sorteador_app
      - node_sorteador_app
      - react_sorteador_app

volumes:
  postgres_sorteador_app:
  build_react:
  